# Default values for astrid.
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

api:
  replicaCount: 2
  
  image:
    repository: registry.digitalocean.com/astrid-registry/astrid-api
    tag: "v0.1.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  # Resource limits and requests for predictable scheduling
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Environment variables
  env:
    LOG_LEVEL: "INFO"
    CORS_ALLOWED_ORIGINS: ""
    REDIS_URL: "redis://redis:6379/0"
    CELERY_BROKER_URL: "redis://redis:6379/0"
    CELERY_RESULT_BACKEND: "redis://redis:6379/0"

  # Enable secret-based environment variables
  envFromSecret: true

  # Horizontal Pod Autoscaler configuration
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # Pod Disruption Budget
  pdb:
    enabled: true
    minAvailable: 1

  # Network policies
  networkPolicy:
    enabled: true
    ingressRules:
      - from:
          - namespaceSelector:
              matchLabels:
                name: ingress-nginx
        ports:
          - protocol: TCP
            port: 80

  # Pod security standards
  podSecurity:
    enabled: true
    level: "restricted"
    version: "latest"

  nodeSelector: {}

  tolerations: []

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - {{ include "astrid.name" . }}
            topologyKey: kubernetes.io/hostname

# Redis configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  persistence:
    enabled: true
    size: 1Gi

# Celery worker configuration
celery:
  enabled: true
  replicaCount: 2
  image:
    repository: registry.digitalocean.com/astrid-registry/astrid-api
    tag: "v0.1.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  command:
    - "celery"
    - "-A"
    - "src.api.celery_app"
    - "worker"
    - "--loglevel=info"
    - "--concurrency=2"

# Image pull secrets for private registry
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""