{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "astrid.fullname" . }}-redis
  labels:
    {{- include "astrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "astrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
